language: ruby

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

cache: bundler

branches:
  # Only build master and release version tags
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - travis

rvm:
  - "2.5"

gemfile:
  - Gemfile
  - gemfiles/activerecord_5.1.gemfile

matrix:
  include:
  - rvm: 2.3
    gemfile: gemfiles/activerecord_5.0.gemfile

script:
  - bundle exec rake spec
