language: ruby
rvm:
  - 2.5
  - 2.3

cache: bundler

branches:
  # Only build master and release version tags
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

gemfile:
  - Gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile

script:
  - bundle exec rake spec
